num_agent: 2
car1:
    name: "car1"
    color: "0000FF" #blue
car2:
    name: "car2"
    color: "00FF00" #green
# car3:
#     name: "car3"
#     color: "FF0000" #red
# car4:
#     name: "car4"
#     color: "800080" #purple
